spring.config.activate.on-profile=docker
spring.datasource.url=jdbc:postgresql://postgres:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=postgrespassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
spring.liquibase.enabled=false
